//! N64 (Nintendo 64) emulation implementation.
//!
//! This module provides a basic N64 system emulator using the MIPS R4300i CPU core
//! from `emu_core`, along with N64-specific components:
//!
//! - **CPU**: MIPS R4300i (64-bit processor running at 93.75 MHz)
//! - **RCP**: Reality Co-Processor (graphics and audio)
//!   - **RDP**: Reality Display Processor (graphics rasterization)
//!   - **RSP**: Reality Signal Processor (geometry/audio processing - stub)
//! - **Memory**: 4MB RDRAM + cartridge ROM
//! - **Timing**: NTSC (~60 Hz frame rate)

#![allow(clippy::upper_case_acronyms)]

mod ai;
mod bus;
mod cartridge;
mod cpu;
mod debugger;
mod mi;
mod pif;
mod rdp;
mod rdp_renderer;
mod rdp_renderer_opengl;
mod rsp;
mod rsp_hle;
mod tlb;
mod vi;

use bus::N64Bus;
use cpu::N64Cpu;
use emu_core::debug::Debugger;
use emu_core::logging::{log, LogCategory, LogLevel};
use emu_core::{types::Frame, MountPointInfo, System};
use thiserror::Error;

#[derive(Error, Debug)]
pub enum N64Error {
    #[error("Invalid ROM format: {0}")]
    InvalidRom(String),
    #[error("No cartridge mounted")]
    NoCartridge,
    #[error("Invalid mount point: {0}")]
    InvalidMountPoint(String),
}

/// Debug information for N64 system
///
/// Provides runtime information about the loaded ROM and system state
/// for display in debug overlays.
#[derive(Debug, Clone)]
pub struct DebugInfo {
    /// ROM name from cartridge header (20 bytes)
    pub rom_name: String,
    /// ROM size in megabytes
    pub rom_size_mb: f32,
    /// Current PC (program counter)
    pub pc: u64,
    /// RSP microcode type
    pub rsp_microcode: String,
    /// Number of vertices in RSP vertex buffer
    pub rsp_vertex_count: usize,
    /// RDP status flags
    pub rdp_status: u32,
    /// Frame buffer resolution
    pub framebuffer_resolution: String,
    /// CPU cycle count
    pub cpu_cycles: u64,
    /// Current frame cycles
    pub frame_cycles: u32,
}

/// N64 system implementation
pub struct N64System {
    cpu: N64Cpu,
    frame_cycles: u32,
    current_cycles: u32,
    /// Instruction tracer for debugging
    instruction_tracer: emu_core::instruction_tracer::InstructionTracer,
    /// Breakpoint manager for debugging
    breakpoint_manager: emu_core::breakpoints::BreakpointManager,
}

// Re-export controller types for convenience
pub use pif::{ControllerButtons, ControllerState};
// Re-export save type for use by the frontend
pub use cartridge::SaveType;

impl N64System {
    /// Create a new N64 system with OpenGL renderer
    /// Requires a GL context for hardware-accelerated rendering
    pub fn new(gl: glow::Context) -> Result<Self, String> {
        let bus = N64Bus::new(gl)?;
        Ok(Self {
            cpu: N64Cpu::new(bus),
            // The N64 CPU runs at 93.75MHz with 60fps NTSC = 1,562,500 cycles/frame
            // Using the correct value ensures games initialize properly
            frame_cycles: 1_562_500,
            current_cycles: 0,
            instruction_tracer: emu_core::instruction_tracer::InstructionTracer::new(),
            breakpoint_manager: emu_core::breakpoints::BreakpointManager::new(),
        })
    }

    /// Create a new N64 system for testing (uses a null GL context)
    ///
    /// NOTE: Tests using this method require `#[ignore]` attribute because the null
    /// GL context will fail when GL functions are actually called.
    /// For proper headless GL testing, glutin+winit would be needed as dev-dependencies,
    /// but this adds complexity. Tests are functional for manual testing with real GL.
    pub fn new_for_test() -> Self {
        // Use null GL context - tests will fail at runtime if GL functions are called
        // Tests are marked as #[ignore] for this reason
        let gl = unsafe { glow::Context::from_loader_function(|_s| std::ptr::null()) };

        Self::new(gl).expect("Failed to create N64 system for test")
    }

    /// Update controller 1 state
    pub fn set_controller1(&mut self, state: ControllerState) {
        self.cpu.bus_mut().set_controller1(state);
    }

    /// Update controller 2 state
    pub fn set_controller2(&mut self, state: ControllerState) {
        self.cpu.bus_mut().set_controller2(state);
    }

    /// Update controller 3 state
    pub fn set_controller3(&mut self, state: ControllerState) {
        self.cpu.bus_mut().set_controller3(state);
    }

    /// Update controller 4 state
    pub fn set_controller4(&mut self, state: ControllerState) {
        self.cpu.bus_mut().set_controller4(state);
    }

    /// Get audio samples from the AI (Audio Interface)
    /// Returns stereo 16-bit PCM samples at the configured sample rate
    ///
    /// # Arguments
    /// * `count` - Number of stereo samples to retrieve
    ///
    /// # Notes
    /// - N64 audio is generated by the game and transferred to AI via DMA
    /// - Sample rate is configured via AI_DACRATE register (typically 44.1kHz)
    /// - Returns silence if buffer is empty
    pub fn get_audio_samples(&mut self, count: usize) -> Vec<i16> {
        self.cpu.bus_mut().ai_mut().get_audio_samples(count)
    }

    /// Get the name of the current renderer backend
    pub fn renderer_name(&self) -> &str {
        self.cpu.bus().rdp().renderer_name()
    }

    /// Get debug information for the GUI overlay
    pub fn get_debug_info(&self) -> DebugInfo {
        let bus = self.cpu.bus();

        // Get ROM name from cartridge header (if available)
        let rom_name = if let Some(cart) = bus.cartridge() {
            // N64 ROM header has game name at offset 0x20 (32 bytes into ROM)
            let name_bytes = cart.read_range(0x20, 20);
            String::from_utf8_lossy(&name_bytes)
                .trim_end_matches('\0')
                .trim()
                .to_string()
        } else {
            "No ROM".to_string()
        };

        // Get ROM size
        let rom_size_mb = if let Some(cart) = bus.cartridge() {
            cart.size() as f32 / (1024.0 * 1024.0)
        } else {
            0.0
        };

        // Get RSP microcode type
        let rsp_microcode = match bus.rsp().microcode_type() {
            rsp_hle::MicrocodeType::F3DEX => "F3DEX".to_string(),
            rsp_hle::MicrocodeType::F3DEX2 => "F3DEX2".to_string(),
            rsp_hle::MicrocodeType::Audio => "Audio".to_string(),
            rsp_hle::MicrocodeType::Unknown => "Unknown".to_string(),
        };

        // Get RSP vertex count
        let rsp_vertex_count = bus.rsp().vertex_count();

        // Get RDP status
        let rdp_status = bus.rdp().read_register(0x0C); // DPC_STATUS register

        // Get framebuffer resolution
        let frame = bus.rdp().get_frame();
        let framebuffer_resolution = format!("{}x{}", frame.width, frame.height);

        DebugInfo {
            rom_name,
            rom_size_mb,
            pc: self.cpu.cpu.pc,
            rsp_microcode,
            rsp_vertex_count,
            rdp_status,
            framebuffer_resolution,
            cpu_cycles: self.cpu.cpu.cycles,
            frame_cycles: self.current_cycles,
        }
    }

    emu_core::impl_instruction_tracer_methods!();

    /// Check if instruction tracing is enabled
    pub fn is_instruction_tracing_enabled(&self) -> bool {
        self.instruction_tracer.is_enabled()
    }

    emu_core::impl_breakpoint_methods!();

    /// Enable or disable breakpoints
    pub fn set_breakpoints_enabled(&mut self, enabled: bool) {
        self.breakpoint_manager.set_enabled(enabled);
    }

    /// Get the breakpoint manager
    pub fn get_breakpoint_manager(&self) -> &emu_core::breakpoints::BreakpointManager {
        &self.breakpoint_manager
    }

    /// Check if the current PC is at an execute breakpoint.
    /// Returns `Some(pc)` if a breakpoint is hit, `None` otherwise.
    pub fn check_breakpoint(&self) -> Option<u32> {
        let pc = self.cpu.cpu.pc as u32;
        if self.breakpoint_manager.should_break_execute(pc) {
            Some(pc)
        } else {
            None
        }
    }

    /// Get debugger interface for this system
    pub fn debugger(&self) -> Option<&dyn emu_core::debug::Debugger> {
        Some(self)
    }

    /// Get the current frame_cycles setting
    pub fn get_frame_cycles(&self) -> u32 {
        self.frame_cycles
    }

    /// Set the frame_cycles for performance tuning
    ///
    /// # Arguments
    /// * `cycles` - Number of CPU cycles to execute per frame (recommended: 50,000 - 200,000)
    ///
    /// # Notes
    /// - Lower values: Better performance, less accurate timing
    /// - Higher values: Worse performance, more accurate timing
    /// - Hardware accurate: 1,562,500 cycles/frame (93.75MHz / 60Hz)
    /// - Default: 50,000 cycles/frame for good performance
    pub fn set_frame_cycles(&mut self, cycles: u32) {
        self.frame_cycles = cycles;
        log(LogCategory::CPU, LogLevel::Info, || {
            format!(
                "N64: Frame cycles set to {} (~{:.2} MHz effective at 60fps)",
                cycles,
                (cycles as f64 * 60.0) / 1_000_000.0
            )
        });
    }

    /// Export the cartridge save data (SRAM, EEPROM, or FlashRAM) for persistence.
    ///
    /// Returns `None` when no save storage is configured for the loaded cartridge.
    /// The format matches what [`Self::set_save_data`] expects, making round-trips
    /// lossless:
    ///
    /// ```no_run
    /// # use emu_n64::N64System;
    /// # fn f(sys: &mut N64System, saved: Vec<u8>) {
    /// // Save
    /// if let Some(data) = sys.get_save_data() {
    ///     std::fs::write("save.bin", &data).ok();
    /// }
    /// // Load
    /// if let Ok(data) = std::fs::read("save.bin") {
    ///     sys.set_save_data(data).ok();
    /// }
    /// # }
    /// ```
    pub fn get_save_data(&self) -> Option<Vec<u8>> {
        self.cpu.bus().get_save_data()
    }

    /// Import previously persisted save data.
    ///
    /// Returns `Err` if the data length does not match the configured save storage,
    /// if no save storage is configured for the current cartridge, or if another
    /// underlying error occurs.
    pub fn set_save_data(&mut self, data: Vec<u8>) -> Result<(), String> {
        self.cpu.bus_mut().set_save_data(data)
    }

    /// Export controller pak (mempak) data for the given controller slot (0-based).
    ///
    /// Returns `None` when no pak is currently inserted in that slot.
    pub fn get_mempak_data(&self, channel: usize) -> Option<Vec<u8>> {
        self.cpu.bus().get_mempak_data(channel)
    }

    /// Import previously persisted controller pak data for a controller slot.
    pub fn set_mempak_data(&mut self, channel: usize, data: Vec<u8>) -> Result<(), String> {
        self.cpu.bus_mut().set_mempak_data(channel, data)
    }

    /// Enable or disable the controller pak in a given controller slot.
    ///
    /// Slot 0 (controller 1) is enabled by default.
    pub fn set_mempak_enabled(&mut self, channel: usize, enabled: bool) {
        self.cpu.bus_mut().set_mempak_enabled(channel, enabled);
    }
}

impl System for N64System {
    type Error = N64Error;

    fn reset(&mut self) {
        self.cpu.reset();
        self.cpu.bus_mut().rdp_mut().reset();
        self.current_cycles = 0;
    }

    fn step_frame(&mut self) -> Result<Frame, Self::Error> {
        self.current_cycles = 0;

        // Log every 60th frame (once per second at 60fps)
        static mut FRAME_COUNTER: u32 = 0;
        unsafe {
            FRAME_COUNTER += 1;
            if FRAME_COUNTER.is_multiple_of(60) {
                let counter = FRAME_COUNTER; // Copy to avoid shared reference
                log(LogCategory::PPU, LogLevel::Info, || {
                    format!("N64: Frame {} complete", counter)
                });
            }
        }

        // NTSC has 262 scanlines per frame
        const SCANLINES_PER_FRAME: u32 = 262;
        let cycles_per_scanline = self.frame_cycles / SCANLINES_PER_FRAME;

        // Execute CPU cycles for one frame, updating VI scanline
        for scanline in 0..SCANLINES_PER_FRAME {
            let target_cycles = (scanline + 1) * cycles_per_scanline;

            // Execute CPU until we reach the cycles for this scanline
            while self.current_cycles < target_cycles {
                // Capture PC before execution for tracing
                let pc_before = self.cpu.cpu.pc as u32;

                let cycles = self.cpu.step();
                self.current_cycles += cycles;

                // Record instruction in tracer if enabled
                if self.instruction_tracer.is_enabled() {
                    if let Some(instruction) = self.disassemble_instruction(pc_before) {
                        let cpu_state = self.get_cpu_state();
                        self.instruction_tracer.trace(instruction, cpu_state);
                    }
                }
            }

            // Check for pending interrupts once per scanline (performance optimization)
            // This is much faster than checking every instruction
            let bus = self.cpu.bus();
            let pending = bus.mi().get_pending_interrupts();
            if pending != 0 {
                // On real N64, ALL MI interrupts are OR'd and routed to CPU IP2
                // (interrupt line 2). Individual MI interrupt bits are distinguished
                // by reading MI_INTR_REG, not by separate CPU interrupt lines.
                self.cpu.cpu.set_interrupt(2);
            } else {
                // Clear IP2 when no MI interrupts are pending
                self.cpu.cpu.clear_interrupt(2);
            }

            // Update VI scanline and check for interrupt
            let bus = self.cpu.bus_mut();
            if bus.vi_mut().update_scanline(scanline) {
                // VI interrupt triggered - set interrupt in MI (only if not already set)
                let mi_status = bus.mi().get_interrupt_status();
                if (mi_status & crate::mi::MI_INTR_VI) == 0 {
                    bus.mi_mut().set_interrupt(crate::mi::MI_INTR_VI);

                    log(LogCategory::Interrupts, LogLevel::Info, || {
                        format!("N64: VI interrupt triggered at scanline {}", scanline)
                    });
                }
            }
        }

        // Get frame from VI framebuffer readback (primary display method)
        // The game renders to RDRAM, and VI reads from RDRAM at VI_ORIGIN
        if let Some(vi_frame) = self.cpu.bus().read_vi_framebuffer() {
            return Ok(vi_frame);
        }

        // Fallback: return RDP internal frame (for cases where VI isn't configured yet)
        let frame = self.cpu.bus().rdp().get_frame().clone();
        Ok(frame)
    }

    fn save_state(&self) -> serde_json::Value {
        serde_json::json!({
            "version": 1,
            "cpu": {
                "gpr": self.cpu.cpu.gpr,
                "pc": self.cpu.cpu.pc,
                "hi": self.cpu.cpu.hi,
                "lo": self.cpu.cpu.lo,
                "cycles": self.cpu.cpu.cycles,
            }
        })
    }

    fn load_state(&mut self, v: &serde_json::Value) -> Result<(), serde_json::Error> {
        if let Some(cpu_state) = v.get("cpu") {
            if let Some(gpr_array) = cpu_state["gpr"].as_array() {
                for (i, val) in gpr_array.iter().enumerate() {
                    if i < 32 {
                        self.cpu.cpu.gpr[i] = val.as_u64().unwrap_or(0);
                    }
                }
            }
            self.cpu.cpu.pc = cpu_state["pc"].as_u64().unwrap_or(0);
            self.cpu.cpu.hi = cpu_state["hi"].as_u64().unwrap_or(0);
            self.cpu.cpu.lo = cpu_state["lo"].as_u64().unwrap_or(0);
            self.cpu.cpu.cycles = cpu_state["cycles"].as_u64().unwrap_or(0);
        }
        Ok(())
    }

    fn supports_save_states(&self) -> bool {
        true
    }

    fn mount_points(&self) -> Vec<MountPointInfo> {
        vec![MountPointInfo {
            id: "Cartridge".to_string(),
            name: "Cartridge Slot".to_string(),
            extensions: vec!["z64".to_string(), "n64".to_string(), "v64".to_string()],
            required: true,
        }]
    }

    fn mount(&mut self, mount_point_id: &str, data: &[u8]) -> Result<(), Self::Error> {
        if mount_point_id != "Cartridge" {
            return Err(N64Error::InvalidMountPoint(mount_point_id.to_string()));
        }

        self.cpu.bus_mut().load_cartridge(data)?;
        self.reset();
        Ok(())
    }

    fn unmount(&mut self, mount_point_id: &str) -> Result<(), Self::Error> {
        if mount_point_id != "Cartridge" {
            return Err(N64Error::InvalidMountPoint(mount_point_id.to_string()));
        }

        self.cpu.bus_mut().unload_cartridge();
        Ok(())
    }

    fn is_mounted(&self, mount_point_id: &str) -> bool {
        mount_point_id == "Cartridge" && self.cpu.bus().has_cartridge()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use emu_core::cpu_mips_r4300i::MemoryMips;

    // NOTE: N64 tests use null GL context and are marked as #[ignore].
    // For proper headless GL testing, glutin+winit would be needed as dev-dependencies.
    // Tests are functional for manual testing with: cargo test --package emu_n64 -- --ignored
    // (requires actual OpenGL 3.3+ support on the system)

    #[test]
    #[ignore] // Requires OpenGL context
    fn test_system_creation() {
        let sys = N64System::new_for_test();
        assert!(!sys.is_mounted("Cartridge"));
    }

    #[test]
    #[ignore] // Requires OpenGL context
    fn test_mount_points() {
        let sys = N64System::new_for_test();
        let mounts = sys.mount_points();
        assert_eq!(mounts.len(), 1);
        assert_eq!(mounts[0].id, "Cartridge");
        assert_eq!(mounts[0].extensions.len(), 3);
    }

    #[test]
    #[ignore] // Requires OpenGL context
    fn test_reset() {
        let mut sys = N64System::new_for_test();
        sys.reset();
        // Should not panic
    }

    #[test]
    #[ignore] // Requires OpenGL context
    fn test_save_load_state() {
        let sys = N64System::new_for_test();
        let state = sys.save_state();

        let mut sys2 = N64System::new_for_test();
        assert!(sys2.load_state(&state).is_ok());
    }

    #[test]
    #[ignore] // Requires OpenGL context
    fn test_rdp_integration() {
        let sys = N64System::new_for_test();
        let frame = sys.cpu.bus().rdp().get_frame();
        assert_eq!(frame.width, 320);
        assert_eq!(frame.height, 240);
        assert_eq!(frame.pixels.len(), 320 * 240);
    }

    #[test]
    #[ignore] // Requires OpenGL context
    fn test_rdp_register_access() {
        use emu_core::cpu_mips_r4300i::MemoryMips;

        let mut sys = N64System::new_for_test();
        let bus = sys.cpu.bus_mut();

        // Write to RDP START register
        bus.write_word(0x04100000, 0x00123456);
        assert_eq!(bus.read_word(0x04100000), 0x00123456);

        // Write to RDP END register
        bus.write_word(0x04100004, 0x00789ABC);
        assert_eq!(bus.read_word(0x04100004), 0x00789ABC);

        // Read STATUS register
        let status = bus.read_word(0x0410000C);
        assert_ne!(status, 0); // Should have CBUF_READY bit set
    }

    #[test]
    #[ignore] // Requires OpenGL context
    fn test_step_frame_returns_rdp_frame() {
        let mut sys = N64System::new_for_test();
        let result = sys.step_frame();
        assert!(result.is_ok());

        let frame = result.unwrap();
        assert_eq!(frame.width, 320);
        assert_eq!(frame.height, 240);
    }

    // N64 smoke tests have been removed as the simple test ROMs don't work in known-good emulators.
    // For comprehensive N64 testing, use n64-systemtest: https://github.com/lemmy-64/n64-systemtest
    // See test_roms/n64/README.md for details on building and running n64-systemtest.

    #[test]
    #[ignore] // Requires OpenGL context
    fn test_mi_register_access() {
        // Test that MI registers can be accessed through memory bus
        let mut sys = N64System::new_for_test();
        let bus = sys.cpu.bus_mut();

        // Test reading MI_VERSION
        let version = bus.read_word(0x04300004);
        assert_eq!(version, 0x02020102);

        // Test writing to MI_INTR_MASK (enable VI interrupt)
        bus.write_word(0x0430000C, 0x0800); // Set VI interrupt mask
        let mask = bus.read_word(0x0430000C);
        assert_eq!(mask, 0x08); // VI interrupt bit should be set

        // Test reading MI_INTR (should be 0 initially)
        let intr = bus.read_word(0x04300008);
        assert_eq!(intr, 0);
    }

    #[test]
    #[ignore] // Requires OpenGL context
    fn test_vi_interrupt_generation() {
        // Test that VI generates interrupts when scanline matches VI_INTR
        let mut sys = N64System::new_for_test();

        // Enable VI interrupt in MI_INTR_MASK
        sys.cpu.bus_mut().write_word(0x0430000C, 0x0800);

        // Set VI_INTR to trigger on scanline 100 (stored as 200)
        sys.cpu.bus_mut().write_word(0x0440000C, 200);

        // Initially no interrupt
        let intr = sys.cpu.bus().read_word(0x04300008);
        assert_eq!(intr, 0, "No interrupt should be pending initially");

        // Manually trigger VI interrupt by updating scanline
        let should_trigger = sys.cpu.bus_mut().vi_mut().update_scanline(100);
        assert!(should_trigger, "VI should signal interrupt on scanline 100");

        // Set the interrupt in MI
        if should_trigger {
            sys.cpu
                .bus_mut()
                .mi_mut()
                .set_interrupt(crate::mi::MI_INTR_VI);
        }

        // Verify interrupt is now pending
        let intr = sys.cpu.bus().read_word(0x04300008);
        assert_eq!(intr, 0x08, "VI interrupt should be pending");

        // Verify MI reports pending interrupt
        assert!(sys.cpu.bus().mi().has_pending_interrupt());
    }

    #[test]
    #[ignore] // Requires OpenGL context
    fn test_interrupt_acknowledge() {
        // Test that writing to MI_INTR clears the interrupt
        let mut sys = N64System::new_for_test();

        // Set VI interrupt
        sys.cpu
            .bus_mut()
            .mi_mut()
            .set_interrupt(crate::mi::MI_INTR_VI);
        let intr = sys.cpu.bus().read_word(0x04300008);
        assert_eq!(intr, 0x08);

        // Clear interrupt by writing to MI_INTR
        sys.cpu.bus_mut().write_word(0x04300008, 0x08);
        let intr = sys.cpu.bus().read_word(0x04300008);
        assert_eq!(intr, 0, "Interrupt should be cleared");
    }

    #[test]
    #[ignore] // Requires OpenGL context
    fn test_cpu_interrupt_handling() {
        // Test that CPU responds to interrupts
        let mut sys = N64System::new_for_test();

        // Enable interrupts in CPU Status register
        // Set IE (bit 0) and enable interrupt 3 (VI) in IM field (bit 11)
        let status = sys.cpu.cpu.cp0[12]; // CP0_STATUS
        sys.cpu.cpu.cp0[12] = status | 0x01 | (1 << 11); // IE=1, IM3=1

        // Set a known PC
        sys.cpu.cpu.pc = 0x80000000;

        // Trigger an interrupt in CPU
        sys.cpu.cpu.set_interrupt(3); // VI interrupt

        // Check that interrupt is pending in Cause register
        let cause = sys.cpu.cpu.cp0[13]; // CP0_CAUSE
        assert_ne!(
            cause & (1 << 11),
            0,
            "Interrupt 3 should be pending in Cause"
        );

        // Execute one instruction - should handle interrupt
        let old_pc = sys.cpu.cpu.pc;
        sys.cpu.step();

        // After interrupt, PC should be at exception vector
        assert_eq!(
            sys.cpu.cpu.pc, 0x80000180,
            "PC should jump to exception vector"
        );

        // EPC should contain the return address
        let epc = sys.cpu.cpu.cp0[14]; // CP0_EPC
        assert_eq!(epc, old_pc, "EPC should contain return address");

        // EXL bit should be set in Status
        let status = sys.cpu.cpu.cp0[12];
        assert_ne!(status & 0x02, 0, "EXL bit should be set in Status");
    }

    #[test]
    #[ignore] // Requires OpenGL context
    fn test_full_interrupt_flow() {
        // Integration test: VI generates interrupt, MI propagates it, CPU handles it
        let mut sys = N64System::new_for_test();

        // Setup: Enable interrupts in CPU and MI
        let status = sys.cpu.cpu.cp0[12];
        sys.cpu.cpu.cp0[12] = status | 0x01 | (1 << 11); // IE=1, IM3=1
        sys.cpu.bus_mut().write_word(0x0430000C, 0x0800); // Enable VI in MI

        // Set VI_INTR to trigger on scanline 50
        sys.cpu.bus_mut().write_word(0x0440000C, 100); // Scanline 50 * 2

        // Set a known PC
        sys.cpu.cpu.pc = 0x80000000;
        let old_pc = sys.cpu.cpu.pc;

        // Trigger VI interrupt manually (simulating what happens during frame execution)
        let should_trigger = sys.cpu.bus_mut().vi_mut().update_scanline(50);
        assert!(should_trigger);

        sys.cpu
            .bus_mut()
            .mi_mut()
            .set_interrupt(crate::mi::MI_INTR_VI);
        sys.cpu.cpu.set_interrupt(3);

        // Execute instruction - should handle interrupt
        sys.cpu.step();

        // Verify interrupt was handled
        assert_eq!(
            sys.cpu.cpu.pc, 0x80000180,
            "PC should be at exception vector"
        );
        assert_eq!(
            sys.cpu.cpu.cp0[14], old_pc,
            "EPC should contain return address"
        );
    }

    #[test]
    #[ignore] // Requires OpenGL context
    fn test_controller_input_integration() {
        // Test that controller input flows from system to PIF correctly
        use emu_core::cpu_mips_r4300i::MemoryMips;

        let mut sys = N64System::new_for_test();

        // Create a controller state with some buttons pressed
        let mut controller_state = crate::pif::ControllerState::default();
        controller_state.buttons.a = true;
        controller_state.buttons.start = true;
        controller_state.buttons.d_up = true;
        controller_state.stick_x = 64;
        controller_state.stick_y = -32;

        // Set controller 1 state
        sys.set_controller1(controller_state);

        // Simulate game reading controller via PIF RAM (at 0x1FC007C0)
        let bus = sys.cpu.bus_mut();

        // Write controller read command
        bus.write_byte(0x1FC007C0, 0x01); // T=1 byte
        bus.write_byte(0x1FC007C1, 0x04); // R=4 bytes
        bus.write_byte(0x1FC007C2, 0x01); // Command 0x01 (read controller)

        // Read response
        let buttons_hi = bus.read_byte(0x1FC007C3);
        let buttons_lo = bus.read_byte(0x1FC007C4);
        let stick_x = bus.read_byte(0x1FC007C5) as i8;
        let stick_y = bus.read_byte(0x1FC007C6) as i8;

        // Verify button bits (A=bit 15, Start=bit 12, D-Up=bit 11)
        let buttons = u16::from_be_bytes([buttons_hi, buttons_lo]);
        assert_ne!(buttons & (1 << 15), 0, "A button should be pressed");
        assert_ne!(buttons & (1 << 12), 0, "Start button should be pressed");
        assert_ne!(buttons & (1 << 11), 0, "D-Up should be pressed");
        assert_eq!(buttons & (1 << 14), 0, "B button should not be pressed");

        // Verify analog stick
        assert_eq!(stick_x, 64);
        assert_eq!(stick_y, -32);
    }

    #[test]
    #[ignore] // Requires OpenGL context
    fn test_controller_multi_player() {
        // Test that multiple controllers work independently
        use emu_core::cpu_mips_r4300i::MemoryMips;

        let mut sys = N64System::new_for_test();

        // Set different states for controllers 1 and 2
        let mut state1 = crate::pif::ControllerState::default();
        state1.buttons.a = true;
        sys.set_controller1(state1);

        let mut state2 = crate::pif::ControllerState::default();
        state2.buttons.b = true;
        sys.set_controller2(state2);

        let bus = sys.cpu.bus_mut();

        // Read controller 1 (at 0x1FC007C0)
        bus.write_byte(0x1FC007C0, 0x01);
        bus.write_byte(0x1FC007C1, 0x04);
        bus.write_byte(0x1FC007C2, 0x01);
        let buttons1 = u16::from_be_bytes([bus.read_byte(0x1FC007C3), bus.read_byte(0x1FC007C4)]);

        // Read controller 2 (at 0x1FC007C8)
        bus.write_byte(0x1FC007C8, 0x01);
        bus.write_byte(0x1FC007C9, 0x04);
        bus.write_byte(0x1FC007CA, 0x01);
        let buttons2 = u16::from_be_bytes([bus.read_byte(0x1FC007CB), bus.read_byte(0x1FC007CC)]);

        // Verify controller 1 has A pressed
        assert_ne!(buttons1 & (1 << 15), 0);
        assert_eq!(buttons1 & (1 << 14), 0);

        // Verify controller 2 has B pressed
        assert_eq!(buttons2 & (1 << 15), 0);
        assert_ne!(buttons2 & (1 << 14), 0);
    }

    #[test]
    #[ignore] // Requires OpenGL context
    fn test_n64_renderer_name() {
        // Test that renderer_name() reports the correct renderer
        // NOTE: Requires actual OpenGL 3.3+ to run
        let sys = N64System::new_for_test();

        // By default, should be using OpenGL renderer
        let renderer_name = sys.renderer_name();
        assert!(
            renderer_name.contains("OpenGL"),
            "Expected OpenGL renderer by default, got {}",
            renderer_name
        );
    }
}
